// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-jP9bl91DbqZuRnqB5p70wEybuEv4AY',
    appId: '1:1080188885419:web:2d6c2ebdddbdaf55015aee',
    messagingSenderId: '1080188885419',
    projectId: 'bms-sample-c79d5',
    authDomain: 'bms-sample-c79d5.firebaseapp.com',
    databaseURL: 'https://bms-sample-c79d5-default-rtdb.firebaseio.com',
    storageBucket: 'bms-sample-c79d5.appspot.com',
    measurementId: 'G-9ZZYSEJGQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Sn3JuophTvviBI7Juy978um3dpqw5Js',
    appId: '1:1080188885419:android:bc145f01594d02c4015aee',
    messagingSenderId: '1080188885419',
    projectId: 'bms-sample-c79d5',
    databaseURL: 'https://bms-sample-c79d5-default-rtdb.firebaseio.com',
    storageBucket: 'bms-sample-c79d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAq6vxLTwG6s4yfR5Xu0z-AA30Wq06A2I',
    appId: '1:1080188885419:ios:a32917620f0d4948015aee',
    messagingSenderId: '1080188885419',
    projectId: 'bms-sample-c79d5',
    databaseURL: 'https://bms-sample-c79d5-default-rtdb.firebaseio.com',
    storageBucket: 'bms-sample-c79d5.appspot.com',
    iosBundleId: 'com.example.bmsSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAq6vxLTwG6s4yfR5Xu0z-AA30Wq06A2I',
    appId: '1:1080188885419:ios:f2b22259d2cf33bc015aee',
    messagingSenderId: '1080188885419',
    projectId: 'bms-sample-c79d5',
    databaseURL: 'https://bms-sample-c79d5-default-rtdb.firebaseio.com',
    storageBucket: 'bms-sample-c79d5.appspot.com',
    iosBundleId: 'com.example.bmsSample.RunnerTests',
  );
}
